CREATE TABLE IF NOT EXISTS `#__tinypayment_paymentinfo` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`pay_title` varchar(100) NOT NULL,
	`pay_description` text NOT NULL,
	`payer_name` varchar(250) NOT NULL,
	`payer_mobile` varchar(12) NOT NULL,
	`payer_email` varchar(255) NOT NULL,
	`payer_ip` varchar(255) NOT NULL,
	`admin_description` text NOT NULL,
	`order_status` tinyint(2) DEFAULT '0',
	`create_time` int(11) NOT NULL,
	`edit_time` int(11) NOT NULL,
	`cryptuid` varchar(255) NOT NULL,
	`salt` varchar(255) NOT NULL,
	`uniq` varchar(255) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE IF NOT EXISTS `#__tinypayment_transactions` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`port_id` tinyint(2) UNSIGNED NOT NULL,
	`price` decimal(15,2) NOT NULL,
	`ref_id` varchar(255) COLLATE utf8_persian_ci DEFAULT NULL,
	`tracking_code` varchar(50) COLLATE utf8_persian_ci DEFAULT NULL,
	`cardNumber` varchar(50) COLLATE utf8_persian_ci DEFAULT NULL,
	`status` tinyint(1) NOT NULL DEFAULT '0',
	`payment_date` int(11) NULL DEFAULT NULL,
	`last_change_date` int(11) NOT NULL,
	`payment_id` int(11) NOT NULL,
	`uniq` varchar(255) NOT NULL,
	PRIMARY KEY (`id`),
	KEY (`payment_id`),
	CONSTRAINT `fk_payment_id` FOREIGN KEY (`payment_id`) REFERENCES `#__tinypayment_paymentinfo` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



CREATE TABLE IF NOT EXISTS `#__tinypayment_status_log` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`transaction_id` int(11) NOT NULL,
	`result_code` varchar(250) CHARACTER SET utf8 COLLATE utf8_persian_ci DEFAULT NULL,
	`result_message` varchar(255) CHARACTER SET utf8 COLLATE utf8_persian_ci DEFAULT NULL,
	`log_date` int(11) NOT NULL,
	`uniq` varchar(255) NOT NULL,
	PRIMARY KEY (`id`),
	KEY (`transaction_id`),
	CONSTRAINT `fk_transaction_id` FOREIGN KEY (`transaction_id`) REFERENCES `#__tinypayment_paymentinfo` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE IF NOT EXISTS `#__tinypayment_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `start_date` int(10) NOT NULL,
  `end_date` int(10) NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__tinypayment_form_logs` (
  `id` int(13) NOT NULL AUTO_INCREMENT,
  `user_id` int(15) NOT NULL,
  `user_ip` varchar(255) NOT NULL,
  `request_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `input_string` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `#__tinypayment_msgs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `port_id` tinyint(2) NOT NULL,
  `msg_id` varchar(250) NOT NULL,
  `msg` varchar(250) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO `#__tinypayment_msgs` (`id`, `port_id`, `msg_id`, `msg`) VALUES
(1, 3, '11', 'شماره کارت نامعتبر است'),
(2, 3, '12', 'موجودي کافي نيست'),
(3, 3, '13', 'رمز نادرست است'),
(4, 3, '14', 'تعداد دفعات وارد کردن رمز بيش از حد مجاز است'),
(5, 3, '15', 'کارت نامعتبر است'),
(6, 3, '17', 'کاربر از انجام تراکنش منصرف شده است'),
(7, 3, '18', 'تاريخ انقضاي کارت گذشته است'),
(8, 3, '21', 'پذيرنده نامعتبر است'),
(9, 3, '22', 'ترمينال مجوز ارايه سرويس درخواستي را ندارد'),
(10, 3, '23', 'خطاي امنيتي رخ داده است'),
(11, 3, '24', 'اطلاعات کاربري پذيرنده نامعتبر است'),
(12, 3, '25', 'مبلغ نامعتبر است'),
(13, 3, '31', 'پاسخ نامعتبر است'),
(14, 3, '32', 'فرمت اطلاعات وارد شده صحيح نمي باشد'),
(15, 3, '33', 'حساب نامعتبر است'),
(16, 3, '34', 'خطاي سيستمي'),
(17, 3, '35', 'تاريخ نامعتبر است'),
(18, 3, '41', 'شماره درخواست تکراري است'),
(19, 3, '42', 'تراکنش Sale يافت نشد'),
(20, 3, '43', 'قبلا درخواست Verify داده شده است'),
(21, 3, '44', 'درخواست Verify يافت نشد'),
(22, 3, '45', 'تراکنش Settle شده است'),
(23, 3, '46', 'تراکنش Settle نشده است'),
(24, 3, '47', 'تراکنش Settle يافت نشد'),
(25, 3, '48', 'تراکنش Reverse شده است'),
(26, 3, '49', 'تراکنش Refund يافت نشد'),
(27, 3, '51', 'تراکنش تکراري است'),
(28, 3, '52', 'سرويس درخواستي موجود نمي باشد'),
(29, 3, '54', 'تراکنش مرجع موجود نيست'),
(30, 3, '55', 'تراکنش نامعتبر است'),
(31, 3, '61', 'خطا در واريز'),
(32, 3, '100', 'تراکنش با موفقيت انجام شد.'),
(33, 3, '111', 'صادر کننده کارت نامعتبر است'),
(34, 3, '112', 'خطاي سوئيچ صادر کننده کارت'),
(35, 3, '113', 'پاسخي از صادر کننده کارت دريافت نشد'),
(36, 3, '114', 'دارنده کارت مجاز به انجام اين تراکنش نيست'),
(37, 3, '412', 'شناسه قبض نادرست است'),
(38, 3, '413', 'شناسه پرداخت نادرست است'),
(39, 3, '414', 'سازمان صادر کننده قبض نامعتبر است'),
(40, 3, '415', 'زمان جلسه کاري به پايان رسيده است'),
(41, 3, '416', 'خطا در ثبت اطلاعات'),
(42, 3, '417', 'شناسه پرداخت کننده نامعتبر است'),
(43, 3, '418', 'اشکال در تعريف اطلاعات مشتري'),
(44, 3, '419', 'تعداد دفعات ورود اطلاعات از حد مجاز گذشته است'),
(45, 3, '421', 'IP نامعتبر است'),
(46, 3, '500', 'کاربر به صفحه زرین پال رفته ولي هنوز بر نگشته است'),
(47, 1, '0', 'تراکنش با موفقیت انجام شد'),
(48, 1, '11', 'شماره کارت نامعتبر است'),
(49, 1, '12', 'موجودی کافی نیست'),
(50, 1, '13', 'رمز نادرست است'),
(51, 1, '14', 'تعداد دفعات وارد کردن رمز بیش از حد مجاز است'),
(52, 1, '15', 'کارت نامعتبر است'),
(53, 1, '16', 'دفعات برداشت وجه بیش از حد مجاز است'),
(54, 1, '17', 'کاربر از انجام تراکنش منصرف شده است'),
(55, 1, '18', 'تاریخ انقضای کارت گذشته است'),
(56, 1, '19', 'مبلغ برداشت وجه بیش از حد مجاز است'),
(57, 1, '21', 'پذیرنده نامعتبر است'),
(58, 1, '23', 'خطای امنیتی رخ داده است'),
(59, 1, '24', 'اطلاعات کاربری پذیرنده نادرست است'),
(60, 1, '25', 'مبلغ نامتعبر است'),
(61, 1, '31', 'پاسخ نامتعبر است'),
(62, 1, '32', 'فرمت اطلاعات وارد شده صحیح نمی باشد'),
(63, 1, '33', 'حساب نامعتبر است'),
(64, 1, '34', 'خطای سیستمی'),
(65, 1, '35', 'تاریخ نامعتبر است'),
(66, 1, '41', 'شماره درخواست تکراری است'),
(67, 1, '42', 'تراکنش Sale‌ یافت نشد'),
(68, 1, '43', 'قبلا درخواست Verify‌ داده شده است'),
(69, 1, '44', 'درخواست Verify‌ یافت نشد'),
(70, 1, '45', 'تراکنش Settle‌ شده است'),
(71, 1, '46', 'تراکنش Settle‌ نشده است'),
(72, 1, '47', 'تراکنش  Settle یافت نشد'),
(73, 1, '48', 'تراکنش Reverse شده است'),
(74, 1, '49', 'تراکنش Refund یافت نشد'),
(75, 1, '51', 'تراکنش تکراری است'),
(76, 1, '54', 'تراکنش مرجع موجود نیست'),
(77, 1, '55', 'تراکنش نامعتبر است'),
(78, 1, '61', 'خطا در واریز'),
(79, 1, '111', 'صادر کننده کارت نامعتبر است'),
(80, 1, '112', 'خطا سوییج صادر کننده کارت'),
(81, 1, '113', 'پاسخی از صادر کننده کارت دریافت نشد'),
(82, 1, '114', 'دارنده کارت مجاز به انجام این تراکنش نیست'),
(83, 1, '412', 'شناسه قبض نادرست است'),
(84, 1, '413', 'شناسه پرداخت نادرست است'),
(85, 1, '414', 'سازمان صادر کننده قبض نادرست است'),
(86, 1, '415', 'زمان جلسه کاری به پایان رسیده است'),
(87, 1, '416', 'خطا در ثبت اطلاعات'),
(88, 1, '417', 'شناسه پرداخت کننده نامعتبر است'),
(89, 1, '418', 'اشکال در تعریف اطلاعات مشتری'),
(90, 1, '419', 'تعداد دفعات ورود اطلاعات از حد مجاز گذشته است'),
(91, 1, '421', 'IP‌ نامعتبر است'),
(92, 9, '-1', 'خطای داخل شبکه مالی'),
(93, 9, '-2', 'سپردها برابر نیستند'),
(94, 9, '-3', 'ورودی های حاوی کاراکترهای غیر مجاز می باشد'),
(95, 9, '-4', 'کلمه عبور یا کد فروشنده اشتباه است'),
(96, 9, '-5', 'Database excetion'),
(97, 9, '-6', 'سند قبلا برگشت کامل یافته است'),
(98, 9, '-7', 'رسید دیجیتالی تهی است'),
(99, 9, '-8', 'طول ورودی های بیش از حد مجاز است'),
(100, 9, '-9', 'وجود کاراکترهای غیر مجاز در مبلغ برگشتی'),
(101, 9, '-10', 'رسید دیجیتالی حاوی کاراکترهای غیر مجاز است'),
(102, 9, '-11', 'طول ورودی های کمتر از حد مجاز است'),
(103, 9, '-12', 'مبلغ برگشت منفی است'),
(104, 9, '-13', 'مبلغ برگشتی برای برگشت جزیی بیش از مبلغ برگشت نخورده رسید دیجیتالی است'),
(105, 9, '-14', 'چنین تراکنشی تعریف نشده است'),
(106, 9, '-15', 'مبلغ برگشتی به صورت اعشاری داده شده است'),
(107, 9, '-16', 'خطای داخلی سیستم'),
(108, 9, '-17', 'برگشت زدن جزیی تراکنشی که با کارت بانکی غیر از بانک سامان انجام پذیرفته است'),
(109, 9, '-18', 'IP Adderess‌ فروشنده نامعتبر'),
(125, 9, 'Canceled By User', 'تراکنش توسط خریدار کنسل شده است'),
(126, 9, 'Invalid Amount', 'مبلغ سند برگشتی از مبلغ تراکنش اصلی بیشتر است'),
(127, 9, 'Invalid Transaction', 'درخواست برگشت یک تراکنش رسیده است . در حالی که تراکنش اصلی پیدا نمی شود.'),
(128, 9, 'Invalid Card Number', 'شماره کارت اشتباه است'),
(129, 9, 'No Such Issuer', 'چنین صادر کننده کارتی وجود ندارد'),
(130, 9, 'Expired Card Pick Up', 'از تاریخ انقضا کارت گذشته است و کارت دیگر معتبر نیست'),
(131, 9, 'Allowable PIN Tries Exceeded Pick Up', 'رمز (PIN) کارت ۳ بار اشتباه وارد شده است در نتیجه کارت غیر فعال خواهد شد.'),
(132, 9, 'Incorrect PIN', 'خریدار رمز کارت (PIN) را اشتباه وارده کرده است'),
(133, 9, 'Exceeds Withdrawal Amount Limit', 'مبلغ بیش از سقف برداشت می باشد'),
(134, 9, 'Transaction Cannot Be Completed', 'تراکنش تایید شده است ولی امکان سند خوردن وجود ندارد'),
(135, 9, 'Response Received Too Late', 'تراکنش در شبکه بانکی  timeout خورده است'),
(136, 9, 'Suspected Fraud Pick Up', 'خریدار فیلد CVV2 یا تاریخ انقضا را اشتباه وارد کرده و یا اصلا وارد نکرده است.'),
(137, 9, 'No Sufficient Funds', 'موجودی به اندازه کافی در حساب وجود ندارد'),
(138, 9, 'Issuer Down Slm', 'سیستم کارت بانک صادر کننده در وضعیت عملیاتی نیست'),
(139, 9, 'TME Error', 'کلیه خطاهای دیگر بانکی که باعث ایجاد چنین خطایی می گردد'),
(140, 9, '1', 'تراکنش با موفقیت انجام شده است'),
(141, 0, 'hck', 'شماره درخواست شما تکراری می باشد . لطف مجددا امتحان کنید'),
(142, 0, 'empty', 'در حال حاضر این درگاه غیر فعال می باشد'),
(143, 0, 'hck2', 'لطفا از کاراکترهای مجاز استفاده کنید'),
(144, 0, 'hck3', 'این کاربر یک بات است'),
(145, 0, '1000', 'مبلغ وارد شده کمتر از ۱۰۰۰ ریال است'),
(146, 0, 'token', 'جلسه کاربری شما منقضی شده است');

CREATE TABLE IF NOT EXISTS `#__tinypayment_banks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bank_id` tinyint(2) DEFAULT '0',
  `bank_name` varchar(50) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '0',
  `username` varchar(50) DEFAULT NULL,
  `password` varchar(50) DEFAULT NULL,
  `terminal_code` varchar(50) DEFAULT NULL,
  `test_mode` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `#__tinypayment_banks` (`id`, `bank_id`, `bank_name`, `active`, `username`, `password`, `terminal_code`, `test_mode`) VALUES
(1, 1, 'mellat', 0, 'username', 'password', 'terminalcode', 0),
(2, 3, 'zarinpal', 0, 'username', 'password', 'terminalcode', 1),
(3, 9, 'saman', 0, 'username', 'password', 'terminalcode', 0);


CREATE TABLE IF NOT EXISTS `#__tinypayment_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `time_back` int(2) NOT NULL,
  `show_pdf` tinyint(1) NOT NULL,
  `captcha` tinyint(1) NOT NULL,
  `public_key` text NOT NULL,
  `private_key` text NOT NULL,
  `show_email` tinyint(1) NOT NULL,
  `bootstrap` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `#__tinypayment_settings` (`id`, `time_back`, `show_pdf`, `captcha`, `public_key`, `private_key`, `show_email`, `bootstrap`) VALUES
(1, 10, 1, 0, 'publickey', 'privatekey', 1, 1);
